# Generated by Django 3.2.4 on 2021-06-18 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='duedate',
        ),
    ]
